### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by EricRibeiro** [GitGuardian/gg-shield-orb#2]
Hello GitGuardian team 👋 

I am from the @circleci Community and Partner Engineering team, here to help with a review for the CircleCI orb partnership. I have a few items listed below for changes:

- Fix the "Circle CI" typo in the orb [description](https://github.com/GitGuardian/gg-shield-orb/blob/master/src/%40orb.yml#L4). 

The proper spelling is "CircleCI".

-  Remove the reusable executor.

You need to have the `ggshield` binary in your environment for your orb to work. And the way you are achieving this is by using the image `gitguardian/ggshield`. Meaning if the orb user were to change the executor or the image, your orb wouldn't have the binary and, consequently, won't work.

The best way to address this is by removing your reusable executor and defining it directly in the job. You can refer to [this](https://github.com/CircleCI-Public/github-cli-orb/blob/main/src/jobs/release.yml#L5) example on how to do it.

- Remove the reusable command.

Your command is a single shell command tightly coupled to your image. In this specific use-case, you want to have it as a `run` step in your job instead of a dedicated command:

```
steps:
  - checkout
  - run: ggshield scan ci
```

After addressing the issues above, please provide us with a successful run link. 

Should you have any questions, feel free to post them here, and I'll be happy to help!

**Comment by jeremyds** [comment]
Hello @EricRibeiro,
First, thank you for your long review and explanation, we appreciate it a lot. I am sorry for the long delay to reply to it.

About your second point

> Remove the reusable executor.

Its goal is to allow our users to pin the version of ggshield they want to use. Is there any way to achieve that using the solution you propose?

**Comment by EricRibeiro** [comment]
Hi @jeremyds 👋 

Thank you for looking into it.

You can have the tag parameterized in your job as such:

```
jobs:
  scan:
    parameters:
      base_revision:
        description: pipeline base_revision
        type: string
      revision:
        description: pipeline revision
        type: string
      tag:
        description: Pick a specific gitguardian/ggshield image variant: https://hub.docker.com/r/gitguardian/ggshield/tags
        default: latest
        type: string
    environment:
      CIRCLE_RANGE: << parameters.base_revision >>...<<parameters.revision>>
    docker: 
       - image: gitguardian/ggshield:<<parameters.tag>>
    steps:
      - checkout
      - scan-command
```

Please let me know if you have any other questions.
